# Generated by Django 3.2.20 on 2026-02-06 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Блок голосования')),
                ('active', models.BooleanField(default=False, verbose_name='Активное голосования')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Блок голосования',
                'verbose_name_plural': 'Блоки голосований',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VotePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Пункт голосования')),
                ('theme', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicvotes.theme', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Пункт голосования',
                'verbose_name_plural': 'Пункты голосований',
                'ordering': ['theme__title'],
            },
        ),
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_part', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicvotes.votepart', verbose_name='Голос')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'ordering': ['vote_part__theme__title'],
            },
        ),
    ]
