# Generated by Django 3.2.20 on 2026-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicvotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Текущее голосования'),
        ),
        migrations.AddField(
            model_name='votepart',
            name='sub_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Пункт голосования дополнительный'),
        ),
    ]
