# Generated by Django 3.2.20 on 2026-02-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicvotes', '0002_auto_20260207_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_token',
            field=models.CharField(blank=True, max_length=250, verbose_name='Токен'),
        ),
    ]
