# Generated by Django 3.2.20 on 2026-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicvotes', '0003_theme_theme_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='votepart',
            name='number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2, verbose_name='Номер'),
        ),
    ]
