# Generated by Django 3.2.20 on 2026-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicvotes', '0004_auto_20260207_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecount',
            name='session_token',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Токен сессии'),
        ),
    ]
