# Generated by Django 3.2.20 on 2026-02-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicvotes', '0005_votecount_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='count',
            field=models.DecimalField(decimal_places=0, default=180, max_digits=4, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='theme',
            name='zoom',
            field=models.BooleanField(default=False, verbose_name='Активное голосования'),
        ),
    ]
