# Generated by Django 3.2.20 on 2026-03-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicvotes', '0006_auto_20260208_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='show_timer',
            field=models.BooleanField(default=False, verbose_name='Показывать таймер'),
        ),
    ]
