# Generated by Django 3.2.20 on 2026-03-28 15:29

from django.db import migrations, models
import publicvotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('publicvotes', '0007_theme_show_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='votepart',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=publicvotes.models.make_upload_path, verbose_name='Фото профиля'),
        ),
    ]
