# Generated by Django 3.2.20 on 2026-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicvotes', '0008_votepart_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='main_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст клавной страницы'),
        ),
    ]
