# Generated by Django 3.2.20 on 2026-02-06 15:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('policy_success', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('cookies_agree', models.BooleanField(default=False, verbose_name='Согласие с куки')),
                ('admin_access', models.BooleanField(default=False, verbose_name='Права Администратора')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
